/**
 * AeroMail UI — Design Token System
 * @package @aero-vi/aero-ui
 * @version 2.0.0
 *
 * Single source of truth for all visual constants used across AeroMail.
 * Values derived from Gmail UI research (gmail-research.md) and the
 * AeroMail v2 product specification design tokens (Section 4).
 *
 * Usage:
 *   import { DESIGN_TOKENS } from '@aero-vi/aero-ui'
 *   const bg = DESIGN_TOKENS.colors.dark.BG_MAIN  // '#1f1f1f'
 */
export declare const DARK_COLORS: {
    readonly BG_MAIN: "#1f1f1f";
    readonly BG_APP: "#1f1f1f";
    readonly BG_TOPBAR: "#1f1f1f";
    readonly BG_SIDEBAR: "#1f1f1f";
    readonly BG_ROW_HOVER: "#2d2e30";
    readonly BG_ROW_UNREAD: "#1f2937";
    readonly BG_ROW_SELECTED: "#394457";
    readonly BG_COMPOSE: "#292b2f";
    readonly BG_COMPOSE_HEADER: "#404144";
    readonly BG_CARD: "#2d2d2f";
    readonly BG_CARD_EXPANDED: "#292b2f";
    readonly BG_INPUT: "#303134";
    readonly BG_SETTINGS: "#1f1f1f";
    readonly BG_MODAL_OVERLAY: "rgba(0,0,0,0.5)";
    readonly BG_ACCOUNT_SWITCHER: "#2d2d2f";
    readonly TEXT_PRIMARY: "#e8eaed";
    readonly TEXT_SECONDARY: "#9aa0a6";
    readonly TEXT_SENDER_READ: "#9aa0a6";
    readonly TEXT_SENDER_UNREAD: "#e8eaed";
    readonly TEXT_SUBJECT_UNREAD: "#e8eaed";
    readonly TEXT_SUBJECT_READ: "#9aa0a6";
    readonly TEXT_SNIPPET: "#9aa0a6";
    readonly TEXT_TIMESTAMP: "#9aa0a6";
    readonly TEXT_TIMESTAMP_UNREAD: "#e8eaed";
    readonly TEXT_LINK: "#8ab4f8";
    readonly TEXT_FOLDER_ACTIVE: "#e8eaed";
    readonly TEXT_FOLDER_INACTIVE: "#e8eaed";
    readonly TEXT_ERROR: "#f28b82";
    readonly TEXT_COMPOSE_HEADER: "#e8eaed";
    readonly ACCENT_BLUE: "#8ab4f8";
    readonly BUTTON_BLUE: "#1a73e8";
    readonly BUTTON_BLUE_HOVER: "#1765cc";
    readonly BUTTON_BLUE_LIGHT: "#0b57d0";
    readonly FAB_TEAL: "#00BCD4";
    readonly FAB_TEAL_ALT: "#1a73e8";
    readonly ACTIVE_PILL: "rgba(138,180,248,0.12)";
    readonly ACTIVE_PILL_HOVER: "rgba(138,180,248,0.20)";
    readonly HOVER_BG: "rgba(255,255,255,0.08)";
    readonly DIVIDER: "rgba(255,255,255,0.12)";
    readonly DIVIDER_ROW: "rgba(255,255,255,0.06)";
    readonly ICON_COLOR: "#9aa0a6";
    readonly ICON_ACTIVE: "#8ab4f8";
    readonly STAR_DEFAULT: "rgba(255,255,255,0.4)";
    readonly STAR_ACTIVE: "#fdd663";
    readonly BADGE_TEXT: "#9aa0a6";
    readonly CHIP_BG: "rgba(138,180,248,0.12)";
    readonly CHECKBOX_BORDER: "#9aa0a6";
    readonly CHECKBOX_CHECKED: "#8ab4f8";
    readonly SCROLL_THUMB: "rgba(255,255,255,0.2)";
};
export declare const LIGHT_COLORS: {
    readonly BG_MAIN: "#ffffff";
    readonly BG_SIDEBAR: "#f6f8fc";
    readonly BG_TOPBAR: "#ffffff";
    readonly BG_ROW_HOVER: "#f2f6fc";
    readonly BG_ROW_UNREAD: "#ffffff";
    readonly BG_INPUT: "#eaf1fb";
    readonly TEXT_PRIMARY: "#202124";
    readonly TEXT_SECONDARY: "#444746";
    readonly TEXT_SENDER_READ: "#444746";
    readonly ACTIVE_PILL: "#d3e3fd";
    readonly ACTIVE_PILL_TEXT: "#041e49";
    readonly DIVIDER: "#e0e0e0";
    readonly BUTTON_BLUE: "#0b57d0";
    readonly ACCENT_BLUE: "#1a73e8";
};
export declare const AVATAR_COLORS: readonly ["#F44336", "#E91E63", "#9C27B0", "#673AB7", "#3F51B5", "#2196F3", "#00BCD4", "#009688", "#4CAF50", "#FF9800", "#FF5722", "#795548"];
/**
 * Deterministically maps a sender name to one of 12 avatar colors.
 * Uses a simple character-code sum modulo 12 — same as Gmail's algorithm.
 */
export declare function getAvatarColor(name: string): string;
export declare const LABEL_COLORS: readonly ["#F44336", "#E91E63", "#9C27B0", "#673AB7", "#3F51B5", "#2196F3", "#00BCD4", "#009688", "#4CAF50", "#FF9800", "#FF5722", "#795548"];
export declare const TYPOGRAPHY: {
    readonly fontUi: "'Google Sans', Roboto, 'Helvetica Neue', Arial, sans-serif";
    readonly fontBody: "Roboto, Arial, sans-serif";
    readonly fontMono: "'Google Sans Mono', 'Courier New', monospace";
    readonly sizeAppTitle: "20px";
    readonly sizeThreadSubject: "22px";
    readonly sizeSettingsTitle: "22px";
    readonly sizeSender: "14px";
    readonly sizeSubject: "14px";
    readonly sizeSnippet: "14px";
    readonly sizeTimestamp: "12px";
    readonly sizeFolderName: "14px";
    readonly sizeLabelsHeader: "11px";
    readonly sizeFabText: "14px";
    readonly sizeComposeHeader: "13px";
    readonly sizeReplyButton: "13px";
    readonly sizeButton: "14px";
    readonly weightRegular: 400;
    readonly weightMedium: 500;
    readonly weightSemiBold: 600;
    readonly weightBold: 700;
};
export declare const SPACING: {
    readonly xs: "4px";
    readonly sm: "8px";
    readonly md: "16px";
    readonly lg: "24px";
    readonly xl: "32px";
    readonly '2xl': "48px";
};
export declare const DIMENSIONS: {
    readonly sidebarWidth: "256px";
    readonly sidebarCollapsedWidth: "72px";
    readonly appBarHeight: "64px";
    readonly appBarHeightMobile: "56px";
    readonly appBarPadding: "16px";
    readonly searchBarWidth: "60%";
    readonly searchBarMaxWidth: "720px";
    readonly searchBarHeight: "46px";
    readonly searchBarBorderRadius: "24px";
    readonly rowHeight: "52px";
    readonly rowHeightMobile: "72px";
    readonly rowPadding: "0 16px";
    readonly avatarSizeXs: "24px";
    readonly avatarSizeSm: "32px";
    readonly avatarSizeMd: "36px";
    readonly avatarSizeLg: "40px";
    readonly avatarSizeXl: "56px";
    readonly avatarFontSize: "14px";
    readonly composeWidth: "560px";
    readonly composeHeightDefault: "480px";
    readonly composeHeightMinimized: "40px";
    readonly composeHeightMaximized: "80vh";
    readonly composeHeaderHeight: "40px";
    readonly composeToolbarHeight: "40px";
    readonly composeBorderRadius: "16px 16px 0 0";
    readonly composeZIndex: 1300;
    readonly fabHeight: "56px";
    readonly fabBorderRadius: "16px";
    readonly threadMaxWidth: "860px";
    readonly messageCardBorderRadius: "8px";
    readonly folderRowHeight: "32px";
    readonly activePillBorderRadius: "0 16px 16px 0";
    readonly labelDotSize: "12px";
    readonly labelSwatchSize: "24px";
    readonly sendButtonBorderRadius: "18px";
    readonly sendButtonHeight: "36px";
    readonly touchTargetMin: "48px";
    readonly settingsNavWidth: "256px";
    readonly settingsContentPadding: "24px 32px";
    readonly accountSwitcherWidth: "360px";
    readonly accountSwitcherWidthMobile: "320px";
    readonly accountAvatarSize: "32px";
};
export declare const BORDER_RADIUS: {
    readonly button: "18px";
    readonly card: "8px";
    readonly input: "4px";
    readonly searchBar: "24px";
    readonly fab: "16px";
    readonly activePill: "0 16px 16px 0";
    readonly accountSwitcher: "16px";
    readonly avatar: "50%";
    readonly drawer: "0";
    readonly compose: "16px 16px 0 0";
    readonly chip: "10px";
    readonly colorSwatch: "50%";
};
export declare const SHADOWS: {
    readonly none: "none";
    readonly level1: "0 1px 2px rgba(0,0,0,0.3)";
    readonly level2: "0 2px 6px rgba(0,0,0,0.3)";
    readonly level3: "0 4px 12px rgba(0,0,0,0.4)";
    readonly level4: "0 6px 24px rgba(0,0,0,0.4)";
    readonly level5: "0 8px 32px rgba(0,0,0,0.6)";
};
export declare const TRANSITIONS: {
    readonly drawerSlide: "225ms cubic-bezier(0, 0, 0.2, 1)";
    readonly rowHover: "150ms ease";
    readonly composeOpen: "200ms ease-out";
    readonly composeMinimize: "150ms ease";
    readonly sidebarCollapse: "300ms cubic-bezier(0.4, 0, 0.6, 1)";
    readonly accountPopover: "150ms ease-out";
    readonly checkboxReveal: "150ms ease";
    readonly toast: "200ms ease";
};
export declare const DESIGN_TOKENS: {
    readonly colors: {
        readonly dark: {
            readonly BG_MAIN: "#1f1f1f";
            readonly BG_APP: "#1f1f1f";
            readonly BG_TOPBAR: "#1f1f1f";
            readonly BG_SIDEBAR: "#1f1f1f";
            readonly BG_ROW_HOVER: "#2d2e30";
            readonly BG_ROW_UNREAD: "#1f2937";
            readonly BG_ROW_SELECTED: "#394457";
            readonly BG_COMPOSE: "#292b2f";
            readonly BG_COMPOSE_HEADER: "#404144";
            readonly BG_CARD: "#2d2d2f";
            readonly BG_CARD_EXPANDED: "#292b2f";
            readonly BG_INPUT: "#303134";
            readonly BG_SETTINGS: "#1f1f1f";
            readonly BG_MODAL_OVERLAY: "rgba(0,0,0,0.5)";
            readonly BG_ACCOUNT_SWITCHER: "#2d2d2f";
            readonly TEXT_PRIMARY: "#e8eaed";
            readonly TEXT_SECONDARY: "#9aa0a6";
            readonly TEXT_SENDER_READ: "#9aa0a6";
            readonly TEXT_SENDER_UNREAD: "#e8eaed";
            readonly TEXT_SUBJECT_UNREAD: "#e8eaed";
            readonly TEXT_SUBJECT_READ: "#9aa0a6";
            readonly TEXT_SNIPPET: "#9aa0a6";
            readonly TEXT_TIMESTAMP: "#9aa0a6";
            readonly TEXT_TIMESTAMP_UNREAD: "#e8eaed";
            readonly TEXT_LINK: "#8ab4f8";
            readonly TEXT_FOLDER_ACTIVE: "#e8eaed";
            readonly TEXT_FOLDER_INACTIVE: "#e8eaed";
            readonly TEXT_ERROR: "#f28b82";
            readonly TEXT_COMPOSE_HEADER: "#e8eaed";
            readonly ACCENT_BLUE: "#8ab4f8";
            readonly BUTTON_BLUE: "#1a73e8";
            readonly BUTTON_BLUE_HOVER: "#1765cc";
            readonly BUTTON_BLUE_LIGHT: "#0b57d0";
            readonly FAB_TEAL: "#00BCD4";
            readonly FAB_TEAL_ALT: "#1a73e8";
            readonly ACTIVE_PILL: "rgba(138,180,248,0.12)";
            readonly ACTIVE_PILL_HOVER: "rgba(138,180,248,0.20)";
            readonly HOVER_BG: "rgba(255,255,255,0.08)";
            readonly DIVIDER: "rgba(255,255,255,0.12)";
            readonly DIVIDER_ROW: "rgba(255,255,255,0.06)";
            readonly ICON_COLOR: "#9aa0a6";
            readonly ICON_ACTIVE: "#8ab4f8";
            readonly STAR_DEFAULT: "rgba(255,255,255,0.4)";
            readonly STAR_ACTIVE: "#fdd663";
            readonly BADGE_TEXT: "#9aa0a6";
            readonly CHIP_BG: "rgba(138,180,248,0.12)";
            readonly CHECKBOX_BORDER: "#9aa0a6";
            readonly CHECKBOX_CHECKED: "#8ab4f8";
            readonly SCROLL_THUMB: "rgba(255,255,255,0.2)";
        };
        readonly light: {
            readonly BG_MAIN: "#ffffff";
            readonly BG_SIDEBAR: "#f6f8fc";
            readonly BG_TOPBAR: "#ffffff";
            readonly BG_ROW_HOVER: "#f2f6fc";
            readonly BG_ROW_UNREAD: "#ffffff";
            readonly BG_INPUT: "#eaf1fb";
            readonly TEXT_PRIMARY: "#202124";
            readonly TEXT_SECONDARY: "#444746";
            readonly TEXT_SENDER_READ: "#444746";
            readonly ACTIVE_PILL: "#d3e3fd";
            readonly ACTIVE_PILL_TEXT: "#041e49";
            readonly DIVIDER: "#e0e0e0";
            readonly BUTTON_BLUE: "#0b57d0";
            readonly ACCENT_BLUE: "#1a73e8";
        };
        readonly avatar: readonly ["#F44336", "#E91E63", "#9C27B0", "#673AB7", "#3F51B5", "#2196F3", "#00BCD4", "#009688", "#4CAF50", "#FF9800", "#FF5722", "#795548"];
        readonly label: readonly ["#F44336", "#E91E63", "#9C27B0", "#673AB7", "#3F51B5", "#2196F3", "#00BCD4", "#009688", "#4CAF50", "#FF9800", "#FF5722", "#795548"];
    };
    readonly typography: {
        readonly fontUi: "'Google Sans', Roboto, 'Helvetica Neue', Arial, sans-serif";
        readonly fontBody: "Roboto, Arial, sans-serif";
        readonly fontMono: "'Google Sans Mono', 'Courier New', monospace";
        readonly sizeAppTitle: "20px";
        readonly sizeThreadSubject: "22px";
        readonly sizeSettingsTitle: "22px";
        readonly sizeSender: "14px";
        readonly sizeSubject: "14px";
        readonly sizeSnippet: "14px";
        readonly sizeTimestamp: "12px";
        readonly sizeFolderName: "14px";
        readonly sizeLabelsHeader: "11px";
        readonly sizeFabText: "14px";
        readonly sizeComposeHeader: "13px";
        readonly sizeReplyButton: "13px";
        readonly sizeButton: "14px";
        readonly weightRegular: 400;
        readonly weightMedium: 500;
        readonly weightSemiBold: 600;
        readonly weightBold: 700;
    };
    readonly spacing: {
        readonly xs: "4px";
        readonly sm: "8px";
        readonly md: "16px";
        readonly lg: "24px";
        readonly xl: "32px";
        readonly '2xl': "48px";
    };
    readonly dimensions: {
        readonly sidebarWidth: "256px";
        readonly sidebarCollapsedWidth: "72px";
        readonly appBarHeight: "64px";
        readonly appBarHeightMobile: "56px";
        readonly appBarPadding: "16px";
        readonly searchBarWidth: "60%";
        readonly searchBarMaxWidth: "720px";
        readonly searchBarHeight: "46px";
        readonly searchBarBorderRadius: "24px";
        readonly rowHeight: "52px";
        readonly rowHeightMobile: "72px";
        readonly rowPadding: "0 16px";
        readonly avatarSizeXs: "24px";
        readonly avatarSizeSm: "32px";
        readonly avatarSizeMd: "36px";
        readonly avatarSizeLg: "40px";
        readonly avatarSizeXl: "56px";
        readonly avatarFontSize: "14px";
        readonly composeWidth: "560px";
        readonly composeHeightDefault: "480px";
        readonly composeHeightMinimized: "40px";
        readonly composeHeightMaximized: "80vh";
        readonly composeHeaderHeight: "40px";
        readonly composeToolbarHeight: "40px";
        readonly composeBorderRadius: "16px 16px 0 0";
        readonly composeZIndex: 1300;
        readonly fabHeight: "56px";
        readonly fabBorderRadius: "16px";
        readonly threadMaxWidth: "860px";
        readonly messageCardBorderRadius: "8px";
        readonly folderRowHeight: "32px";
        readonly activePillBorderRadius: "0 16px 16px 0";
        readonly labelDotSize: "12px";
        readonly labelSwatchSize: "24px";
        readonly sendButtonBorderRadius: "18px";
        readonly sendButtonHeight: "36px";
        readonly touchTargetMin: "48px";
        readonly settingsNavWidth: "256px";
        readonly settingsContentPadding: "24px 32px";
        readonly accountSwitcherWidth: "360px";
        readonly accountSwitcherWidthMobile: "320px";
        readonly accountAvatarSize: "32px";
    };
    readonly borderRadius: {
        readonly button: "18px";
        readonly card: "8px";
        readonly input: "4px";
        readonly searchBar: "24px";
        readonly fab: "16px";
        readonly activePill: "0 16px 16px 0";
        readonly accountSwitcher: "16px";
        readonly avatar: "50%";
        readonly drawer: "0";
        readonly compose: "16px 16px 0 0";
        readonly chip: "10px";
        readonly colorSwatch: "50%";
    };
    readonly shadows: {
        readonly none: "none";
        readonly level1: "0 1px 2px rgba(0,0,0,0.3)";
        readonly level2: "0 2px 6px rgba(0,0,0,0.3)";
        readonly level3: "0 4px 12px rgba(0,0,0,0.4)";
        readonly level4: "0 6px 24px rgba(0,0,0,0.4)";
        readonly level5: "0 8px 32px rgba(0,0,0,0.6)";
    };
    readonly transitions: {
        readonly drawerSlide: "225ms cubic-bezier(0, 0, 0.2, 1)";
        readonly rowHover: "150ms ease";
        readonly composeOpen: "200ms ease-out";
        readonly composeMinimize: "150ms ease";
        readonly sidebarCollapse: "300ms cubic-bezier(0.4, 0, 0.6, 1)";
        readonly accountPopover: "150ms ease-out";
        readonly checkboxReveal: "150ms ease";
        readonly toast: "200ms ease";
    };
    readonly BG_MAIN: "#1f1f1f";
    readonly BG_SIDEBAR: "#1f1f1f";
    readonly BG_ROW_HOVER: "#2d2e30";
    readonly TEXT_PRIMARY: "#e8eaed";
    readonly TEXT_SECONDARY: "#9aa0a6";
    readonly ACCENT_BLUE: "#8ab4f8";
    readonly BUTTON_BLUE: "#1a73e8";
    readonly FAB_TEAL: "#00BCD4";
    readonly ACTIVE_PILL: "rgba(138,180,248,0.12)";
};
